### ISSUE TITLE
TinyMIPS探讨

### ISSUE THREAD

**Issue by skingorz** [MaxXSoft/TinyMIPS#1]
请问计组课设验收怎么给分

**Comment by hermitgreen** [comment]
建议关闭此issue

**Comment by MaxXSoft** [comment]
Sorry for not answering your question.

Please do not confuse related course design with this repo, since GitHub is not a forum to discuss how to cope with the course, but a public place for people to discuss code and ideas. So, this issue will be closed, and hope you do not ask such questions on GitHub issues next time.
